---
  env:
    node: true
    es6: true
  rules:
    eol-last: 0
    no-trailing-spaces: 0
    func-names: 0
    comma-dangle: 0
    no-param-reassign: 0
    no-use-before-define: 0
    global-require: 0
    no-underscore-dangle: 0
    one-var: 0
    one-var-declaration-per-line: 0
    max-len: 0
    valid-jsdoc: 2
    valid-typeof: 2
    typelint: 2
  extends: 'airbnb-base/legacy'
  settings:
    typelint:
      lintNative: true
      modelsDir: './lib/models'
      useCache: false